### PR TITLE
 Add Association property on IRule to associate with a field

### PR DESCRIPTION
**Pull request by psincler**
Adds an Association property to IRule as indicated in issue #11

### CODE REVIEW

**Comment by ahanusa** [comment]
Thanks again for this, I really appreciate your contribution.  I'm really swamped right now, I'm hoping to get to this either today or later tonight!

**Comment by ahanusa** [comment]
This looks good, but I'm thinking it might make more sense to give Association higher precedence over EntityName, if supplied.  What do you think?

**Comment by psincler** [comment]
My only thought for the current logic is if you chain a rule (IfValidThenValidate) and the successor is invalid, it copies the association property up to the parent rule (if an association is not already present).  If you've set an entity name on the parent rule, it would be overwritten if we prefer Association value over entity name.  The parent rule may not apply to the same property as the successor rule.

**Comment by ahanusa** [comment]
Ah, good catch.  Let me think about that some more...

I think I'm going to at least merge your PR, as it's good stuff.  I'll run
by any changes that I think we can make by you before changing anything,
just to make sure I haven't forgotten anything.

Is the Association approach working for you so far?

**Comment by psincler** [comment]
Sounds good.  Yes, it is working fine for us after some minor rework on our side.  Just had to create one rule per field validation instead of one rule per field.  It would still be helpful to have multiple error messages per rule.

**Comment by ahanusa** [comment]
Ok, cool.  Regarding the multiple messages per rule request,  can you send
me a sample rule that illustrates the usefulness of this.  Admittedly, I
cannot remember why I decided not to merge my old multi error per rule
branch, but I'm guessing that it was probably for a good reason (aside from
breaking compatibility).

**Comment by ahanusa** [comment]
Ok, all merged.  I noticed that you don't show up as a contributor to peasy after the merge.  You should definitely get acknowledgement for your contribution, is your email linked correctly?

**Comment by psincler** [comment]
Thanks for the merge.  I'll look for a new release to come soon....we want to pick it up ASAP.

Not sure why I don't show up as a contributor.  Emails seem to be linked properly as I get plenty of GitHub notifications.  

As for the business case for multiple error messages per rule, if you use IfValidThenValidate with multiple successors then the engine bails on the first failure.  I think if there was an option to continue validation of all successor rules even when there was a failure then that would give you a way to have effectively have multiple error messages without a breaking change.

After this PR, we have the functionality we need at this time so any further changes would be at your discretion.

**Comment by ahanusa** [comment]
Do you use peasy via nuget, or do you ref the project code directly?

**Comment by ahanusa** [comment]
Ah, I see.  Let me think on that some more.  Also, do you absolutely need
the multiple rules to execute based on the success of a previous successful
execution of a rule?  If not, you can just execute all the rules at the
same level and they will all execute and not short circuit.

**Comment by ahanusa** [comment]
I do like that idea though, and it won't break compatibility either, which
is nice ..

**Comment by psincler** [comment]
We use the nuget pkg.

Sure, we can build the rule chaining in different ways to accomplish our goal....I just had to get into the Peasy code to figure out how it was working.  For now, additional changes are up to you.  If we hit a specific need I'll post an issue or a PR for review.

**Comment by ahanusa** [comment]
Ok, I'll try to get to the nuget deploy this weekend.

Sounds good!

**Comment by ahanusa** [comment]
Hey, you should really get credit for your contribution.

Can you run this command?  `git config --global user.email`

If the result email is not associated with your gmail account (located in https://github.com/settings/profile), that will be the reason why you aren't associated with commits.  Just add it and you should be all good.  

You'll show up in other repos for projects that you've contributed to in the past as well.

**Comment by ahanusa** [comment]
So as it turns out, the addition of the association field broke compatibility anyhow, as anyone who created their own custom rule by implementing `IRule` will now have to provide an implementation for Association.

Not a big deal, however, I'm going to have to bump up the version to 3.0 now anyhow.  That said, if we're going to add support for multiple errors, now would be the time to do it.  Are you finding that validating a list of rules that are top level siblings is giving you what you need?  If so, I guess I'd rather just skip the multiple rules support for now.

Also, I tried to create an updated nuget package, and did not have great success for maintaining compatibility.  It seems that nuget has changed quite a bit since last time I generated a package, and the resulting .nupkg file cannot be installed via .NET Core projects.

So unfortunately it's going to take some time reading up on the docs and figuring out what changed and how I need to tweak the project and .nuspec files.

I'll let you know when I get a new package out, but it may be a while yet.  Are you just using a project reference at this point?  What version of .NET are you using?

**Comment by psincler** [comment]
Not sure what you're running into with nuget.  We are using a nuget package hosted on our private feed for now.  Seems to be working fine on .NET Core.  

I didn't mess with the Pre2017 project.  I just compiled in Release mode in VS.NET and then this is all I did to get it built:

.\nuget.exe pack -Version 3.0.0 Peasy.nuspec

**Comment by ahanusa** [comment]
I got it figured out.  I'll have a nuget release publicly available shortly.

**Pull request merged**
